// Copyright (c) 2026 VH & Co BV. Licensed under the Business Source License 1.1. See LICENSE for details.

package ansible

import (
	"time"

	"github.com/michielvha/stackweaver/backend/internal/api/v2/jsonapi"
	"github.com/michielvha/stackweaver/core/models"
)

// Typed Ansible job wire shapes (#760).

// JobAttributes: the always-null and conditionally-set members mirror the map builder exactly.
// SliceGroupID, RunnerID, StartedAt and FinishedAt are pointers because the old map emitted
// them as null until set - present either way.
type JobAttributes struct {
	Name             string                  `json:"name"`
	JobType          models.AnsibleJobType   `json:"job-type"`
	Status           models.AnsibleJobStatus `json:"status"`
	ExtraVars        models.JobExtraVars     `json:"extra-vars"`
	Limit            string                  `json:"limit"`
	Tags             string                  `json:"tags"`
	SkipTags         string                  `json:"skip-tags"`
	Verbosity        int                     `json:"verbosity"`
	Forks            int                     `json:"forks"`
	BecomeEnabled    bool                    `json:"become-enabled"`
	SliceNumber      int                     `json:"slice-number"`
	SliceCount       int                     `json:"slice-count"`
	SliceGroupID     *string                 `json:"slice-group-id"`
	RunnerID         *string                 `json:"runner-id"`
	DiffMode         bool                    `json:"diff-mode"`
	AnsibleVersion   string                  `json:"ansible-version"`
	ExitCode         *int                    `json:"exit-code"`
	ErrorMessage     string                  `json:"error-message"`
	StartedAt        *string                 `json:"started-at"`
	FinishedAt       *string                 `json:"finished-at"`
	HostsTotal       int                     `json:"hosts-total"`
	HostsOk          int                     `json:"hosts-ok"`
	HostsChanged     int                     `json:"hosts-changed"`
	HostsFailed      int                     `json:"hosts-failed"`
	HostsUnreachable int                     `json:"hosts-unreachable"`
	HostsSkipped     int                     `json:"hosts-skipped"`
	HostsRescued     int                     `json:"hosts-rescued"`
	HostsIgnored     int                     `json:"hosts-ignored"`
	HasWarnings      bool                    `json:"has-warnings"`
	WarningsCount    int                     `json:"warnings-count"`
	CreatedAt        string                  `json:"created-at"`
	UpdatedAt        string                  `json:"updated-at"`

	// Ad hoc jobs only (transient playbook generated by the runner).
	Module     string `json:"module,omitempty"`
	ModuleArgs string `json:"module-args,omitempty"`

	AgentPoolName string `json:"agent-pool-name,omitempty"`
	RunnerName    string `json:"runner-name,omitempty"`
}

// JobRelationships: project and inventory always; the rest per the job's wiring.
type JobRelationships struct {
	Project     jsonapi.Relationship      `json:"project"`
	Inventory   jsonapi.Relationship      `json:"inventory"`
	Playbook    *jsonapi.Relationship     `json:"playbook,omitempty"`
	Template    *jsonapi.Relationship     `json:"template,omitempty"`
	Credentials *jsonapi.ManyRelationship `json:"credentials,omitempty"`
	CreatedBy   *jsonapi.Relationship     `json:"created-by,omitempty"`
	AgentPool   *jsonapi.Relationship     `json:"agent-pool,omitempty"`
	Runner      *jsonapi.Relationship     `json:"runner,omitempty"`
}

// EventAttributes is a full ansible-job-events resource. EventData is the runner's own payload,
// forwarded (or projected) verbatim: Stackweaver does not own Ansible's event schema, so it is
// deliberately a map - the same reasoning as the Zitadel passthroughs in #755.
type EventAttributes struct {
	Counter   int                 `json:"counter"`
	EventType string              `json:"event-type"`
	EventData models.JobExtraVars `json:"event-data"`
	Host      string              `json:"host"`
	Task      string              `json:"task"`
	Play      string              `json:"play"`
	Role      string              `json:"role"`
	Stdout    string              `json:"stdout"`
	Stderr    string              `json:"stderr"`
	Changed   bool                `json:"changed"`
	Failed    bool                `json:"failed"`
	Skipped   bool                `json:"skipped"`
	Timestamp string              `json:"timestamp"`
	CreatedAt string              `json:"created-at"`
	Summary   bool                `json:"summary,omitempty"`
}

// EventRelationships points an event at its job.
type EventRelationships struct {
	Job jsonapi.Relationship `json:"job"`
}

// Typed workflow wire shapes (#760). Nodes and edges ride INLINE as full resources inside the
// workflow's relationships on the show endpoint, so those members are typed as slices of the
// full resource rather than bare identifiers - preserved from the map-based decoration.

// WorkflowAttributes: timestamps are time.Time here because the map builder emitted the raw
// values (RFC3339 with nanoseconds), unlike the second-precision strings elsewhere.
type WorkflowAttributes struct {
	Name                 string    `json:"name"`
	Description          string    `json:"description"`
	AllowSimultaneous    bool      `json:"allow-simultaneous"`
	AskVariablesOnLaunch bool      `json:"ask-variables-on-launch"`
	AskInventoryOnLaunch bool      `json:"ask-inventory-on-launch"`
	AskLimitOnLaunch     bool      `json:"ask-limit-on-launch"`
	ExtraVars            string    `json:"extra-vars"`
	Limit                string    `json:"limit"`
	SurveyEnabled        bool      `json:"survey-enabled"`
	CreatedAt            time.Time `json:"created-at"`
	UpdatedAt            time.Time `json:"updated-at"`
}

// WorkflowNodesRelationship carries full node resources inline.
type WorkflowNodesRelationship struct {
	Data []jsonapi.Resource[WorkflowNodeAttributes] `json:"data"`
}

// WorkflowEdgesRelationship carries full edge resources inline.
type WorkflowEdgesRelationship struct {
	Data []jsonapi.Resource[WorkflowEdgeAttributes] `json:"data"`
}

// WorkflowRelationships: organization always; project/inventory per wiring; nodes/edges only
// on the show endpoint, added by the handler after the base builder.
type WorkflowRelationships struct {
	Organization jsonapi.Relationship       `json:"organization"`
	Project      *jsonapi.Relationship      `json:"project,omitempty"`
	Inventory    *jsonapi.Relationship      `json:"inventory,omitempty"`
	Nodes        *WorkflowNodesRelationship `json:"nodes,omitempty"`
	Edges        *WorkflowEdgesRelationship `json:"edges,omitempty"`
}

// WorkflowResource has mutable relationships so the show handler can attach nodes and edges.
type WorkflowResource struct {
	ID            string                 `json:"id"`
	Type          string                 `json:"type"`
	Attributes    WorkflowAttributes     `json:"attributes"`
	Relationships *WorkflowRelationships `json:"relationships"`
}

// WorkflowNodeAttributes: job-template-name appears only when the template is preloaded.
type WorkflowNodeAttributes struct {
	NodeType               string    `json:"node-type"`
	Identifier             string    `json:"identifier"`
	PositionX              float64   `json:"position-x"`
	PositionY              float64   `json:"position-y"`
	ExtraVars              string    `json:"extra-vars"`
	Limit                  string    `json:"limit"`
	Tags                   string    `json:"tags"`
	SkipTags               string    `json:"skip-tags"`
	Verbosity              int       `json:"verbosity"`
	AllParentsMustConverge bool      `json:"all-parents-must-converge"`
	ApprovalTimeout        int       `json:"approval-timeout"`
	ApprovalMessage        string    `json:"approval-message"`
	CreatedAt              time.Time `json:"created-at"`
	JobTemplateName        string    `json:"job-template-name,omitempty"`
}

// WorkflowNodeRelationships: workflow always; the rest per the node's wiring.
type WorkflowNodeRelationships struct {
	Workflow    jsonapi.Relationship  `json:"workflow"`
	JobTemplate *jsonapi.Relationship `json:"job-template,omitempty"`
	Inventory   *jsonapi.Relationship `json:"inventory,omitempty"`
	Credential  *jsonapi.Relationship `json:"credential,omitempty"`
}

// WorkflowEdgeAttributes is an edge's condition and creation time.
type WorkflowEdgeAttributes struct {
	Condition string    `json:"condition"`
	CreatedAt time.Time `json:"created-at"`
}

// WorkflowEdgeRelationships wires an edge between its nodes.
type WorkflowEdgeRelationships struct {
	Workflow   jsonapi.Relationship `json:"workflow"`
	SourceNode jsonapi.Relationship `json:"source-node"`
	TargetNode jsonapi.Relationship `json:"target-node"`
}

// PlaybookAttributes: LastSyncAt and CachedAt are pointers - the map emitted them as null
// until set, present either way.
type PlaybookAttributes struct {
	Name            string  `json:"name"`
	Description     string  `json:"description"`
	VCSRepository   string  `json:"vcs-repository"`
	VCSBranch       string  `json:"vcs-branch"`
	VCSProvider     string  `json:"vcs-provider"`
	VCSAccountName  string  `json:"vcs-account-name"`
	PlaybookPath    string  `json:"playbook-path"`
	SourceMode      string  `json:"source-mode"`
	LastSyncAt      *string `json:"last-sync-at"`
	LastSyncStatus  string  `json:"last-sync-status"`
	LastSyncCommit  string  `json:"last-sync-commit"`
	LastSyncError   string  `json:"last-sync-error"`
	CachedCommit    string  `json:"cached-commit"`
	CachedAt        *string `json:"cached-at"`
	CachedSizeBytes int64   `json:"cached-size-bytes"`
	CreatedAt       string  `json:"created-at"`
	UpdatedAt       string  `json:"updated-at"`
}

// PlaybookRelationships: project always; vcs-connection when wired.
type PlaybookRelationships struct {
	Project       jsonapi.Relationship  `json:"project"`
	VCSConnection *jsonapi.Relationship `json:"vcs-connection,omitempty"`
}

// JobTemplateAttributes is the ansible-job-templates attribute block. `enabled` inverts the
// stored Disabled flag on the wire.
type JobTemplateAttributes struct {
	Name              string                    `json:"name"`
	Description       string                    `json:"description"`
	ExtraVars         models.InventoryVariables `json:"extra-vars"`
	Limit             string                    `json:"limit"`
	Tags              string                    `json:"tags"`
	SkipTags          string                    `json:"skip-tags"`
	Verbosity         int                       `json:"verbosity"`
	Forks             int                       `json:"forks"`
	BecomeEnabled     bool                      `json:"become-enabled"`
	DiffMode          bool                      `json:"diff-mode"`
	ScheduleEnabled   bool                      `json:"schedule-enabled"`
	ScheduleCron      string                    `json:"schedule-cron"`
	Enabled           bool                      `json:"enabled"`
	TimeoutSeconds    int                       `json:"timeout-seconds"`
	AllowSimultaneous bool                      `json:"allow-simultaneous"`
	RetentionDays     *int                      `json:"retention-days"`
	JobSliceCount     int                       `json:"job-slice-count"`
	AllowCallbacks    bool                      `json:"allow-callbacks"`
	LaunchOnWebhook   bool                      `json:"launch-on-webhook"`
	HostConfigKey     string                    `json:"host-config-key"`
	CreatedAt         string                    `json:"created-at"`
	UpdatedAt         string                    `json:"updated-at"`
}

// JobTemplateRelationships: the fixed trio plus optional credentials and agent pool.
type JobTemplateRelationships struct {
	Project     jsonapi.Relationship      `json:"project"`
	Playbook    jsonapi.Relationship      `json:"playbook"`
	Inventory   jsonapi.Relationship      `json:"inventory"`
	Credentials *jsonapi.ManyRelationship `json:"credentials,omitempty"`
	AgentPool   *jsonapi.Relationship     `json:"agent-pool,omitempty"`
}

// ScheduleAttributes: the trailing string members are omitempty because the map added them
// only when the underlying value was set - a formatted time or status is never the empty
// string, and run-count appeared only when > 0, which omitempty reproduces exactly.
type ScheduleAttributes struct {
	Name           string                `json:"name"`
	Description    string                `json:"description"`
	ScheduleType   models.ScheduleType   `json:"schedule-type"`
	Status         models.ScheduleStatus `json:"status"`
	CronExpression string                `json:"cron-expression"`
	Timezone       string                `json:"timezone"`
	Config         models.ScheduleConfig `json:"config"`
	CreatedAt      string                `json:"created-at"`
	UpdatedAt      string                `json:"updated-at"`
	StartDateTime  string                `json:"start-date-time,omitempty"`
	EndDateTime    string                `json:"end-date-time,omitempty"`
	NextRunAt      string                `json:"next-run-at,omitempty"`
	LastRunAt      string                `json:"last-run-at,omitempty"`
	LastRunStatus  string                `json:"last-run-status,omitempty"`
	RunCount       int                   `json:"run-count,omitempty"`
}

// ScheduleRelationships: organization always; the target and tracking relations only when set.
type ScheduleRelationships struct {
	Organization    jsonapi.Relationship  `json:"organization"`
	JobTemplate     *jsonapi.Relationship `json:"job-template,omitempty"`
	InventorySource *jsonapi.Relationship `json:"inventory-source,omitempty"`
	Playbook        *jsonapi.Relationship `json:"playbook,omitempty"`
	LastJob         *jsonapi.Relationship `json:"last-job,omitempty"`
	CreatedBy       *jsonapi.Relationship `json:"created-by,omitempty"`
}

// WorkflowJobAttributes: StartedAt/FinishedAt are raw pointers (null until set), as the map
// emitted them.
type WorkflowJobAttributes struct {
	Name       string     `json:"name"`
	Status     string     `json:"status"`
	StartedAt  *time.Time `json:"started-at"`
	FinishedAt *time.Time `json:"finished-at"`
	CreatedAt  string     `json:"created-at"`
}

// WorkflowJobOnlyRelationships is the single workflow relationship of a workflow run.
type WorkflowJobOnlyRelationships struct {
	Workflow jsonapi.Relationship `json:"workflow"`
}

// WorkflowNodeJobAttributes is one node of a workflow run.
type WorkflowNodeJobAttributes struct {
	Status     models.WorkflowNodeJobStatus `json:"status"`
	NodeType   models.WorkflowNodeType      `json:"node-type"`
	Identifier string                       `json:"identifier"`
	StartedAt  *time.Time                   `json:"started-at"`
	FinishedAt *time.Time                   `json:"finished-at"`
	Denied     bool                         `json:"denied"`
}

// WorkflowNodeJobRelationships: node always; job and job-template when resolved.
type WorkflowNodeJobRelationships struct {
	Node        jsonapi.Relationship  `json:"node"`
	Job         *jsonapi.Relationship `json:"job,omitempty"`
	JobTemplate *jsonapi.Relationship `json:"job-template,omitempty"`
}

// TotalCountMeta is the bare {"total-count": N} meta block of the workflow-runs listing.
type TotalCountMeta struct {
	TotalCount int64 `json:"total-count"`
}

// GroupAttributes is the ansible-groups attribute block.
type GroupAttributes struct {
	Name        string                    `json:"name"`
	Description string                    `json:"description"`
	Variables   models.InventoryVariables `json:"variables"`
	CreatedAt   string                    `json:"created-at"`
	UpdatedAt   string                    `json:"updated-at"`
}

// GroupRelationships: hosts and children are always emitted, [] when empty.
type GroupRelationships struct {
	Inventory jsonapi.Relationship     `json:"inventory"`
	Hosts     jsonapi.ManyRelationship `json:"hosts"`
	Children  jsonapi.ManyRelationship `json:"children"`
	Parent    *jsonapi.Relationship    `json:"parent,omitempty"`
}

// NotificationTemplateAttributes: config is the decoded stored blob (channel-specific keys
// are not ours to type); the secret is write-only and surfaces only as has-secret.
type NotificationTemplateAttributes struct {
	Name             string                  `json:"name"`
	Description      string                  `json:"description"`
	NotificationType models.NotificationType `json:"notification-type"`
	Config           map[string]interface{}  `json:"config"`
	HasSecret        bool                    `json:"has-secret"`
	CreatedAt        time.Time               `json:"created-at"`
}

// NotificationAttachmentAttributes: the template name rides along only when the relation
// was preloaded.
type NotificationAttachmentAttributes struct {
	OnStarted                bool   `json:"on-started"`
	OnSuccess                bool   `json:"on-success"`
	OnFailure                bool   `json:"on-failure"`
	NotificationTemplateName string `json:"notification-template-name,omitempty"`
}

// NotificationAttachmentRelationships: the template always; exactly one of the two targets.
type NotificationAttachmentRelationships struct {
	NotificationTemplate jsonapi.Relationship  `json:"notification-template"`
	JobTemplate          *jsonapi.Relationship `json:"job-template,omitempty"`
	Workflow             *jsonapi.Relationship `json:"workflow,omitempty"`
}

// ConstructedInputEntry is one ordered input of a constructed inventory. Not a JSON:API
// resource identifier - the member is name, not type, and the frontend reads it that way.
type ConstructedInputEntry struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// InventoryAttributes mixes kebab-case members with the four snake_case VCS ones. That split
// is the shipped wire contract, not an oversight; renaming is a wire change and not this
// task. The VCS members appear only when set, which omitempty reproduces.
type InventoryAttributes struct {
	Name                    string                    `json:"name"`
	Description             string                    `json:"description"`
	InventoryType           models.InventoryType      `json:"inventory-type"`
	Source                  string                    `json:"source"`
	Variables               models.InventoryVariables `json:"variables"`
	LastSyncAt              *time.Time                `json:"last-sync-at"`
	LastSyncStatus          string                    `json:"last-sync-status"`
	LastSyncError           string                    `json:"last-sync-error"`
	LastSyncHostsDiscovered int                       `json:"last-sync-hosts-discovered"`
	LastSyncLog             string                    `json:"last-sync-log"`
	SourceVars              string                    `json:"source-vars"`
	ConstructedLimit        string                    `json:"constructed-limit"`
	ConstructedCacheTimeout int                       `json:"constructed-cache-timeout"`
	CreatedAt               string                    `json:"created-at"`
	UpdatedAt               string                    `json:"updated-at"`
	VCSConnectionID         string                    `json:"vcs_connection_id,omitempty"`
	VCSRepository           string                    `json:"vcs_repository,omitempty"`
	VCSBranch               string                    `json:"vcs_branch,omitempty"`
	InventoryPath           string                    `json:"inventory_path,omitempty"`
	// InputInventories is decorated post-hoc on the detail route for constructed
	// inventories, so it is a slice pointer: absent everywhere else, present (even empty)
	// once set.
	InputInventories *[]ConstructedInputEntry `json:"input-inventories,omitempty"`
}

// InventoryRelationships: the vcs_connection member keeps its snake_case spelling.
type InventoryRelationships struct {
	Organization  jsonapi.Relationship  `json:"organization"`
	VCSConnection *jsonapi.Relationship `json:"vcs_connection,omitempty"`
}

// HostAttributes is the ansible-hosts attribute block.
type HostAttributes struct {
	Name        string                    `json:"name"`
	Description string                    `json:"description"`
	Hostname    string                    `json:"hostname"`
	Port        int                       `json:"port"`
	Variables   models.InventoryVariables `json:"variables"`
	Enabled     bool                      `json:"enabled"`
	CreatedAt   string                    `json:"created-at"`
	UpdatedAt   string                    `json:"updated-at"`
}

// HostRelationships: groups is always emitted, [] when the host is ungrouped.
type HostRelationships struct {
	Inventory jsonapi.Relationship     `json:"inventory"`
	Groups    jsonapi.ManyRelationship `json:"groups"`
}

// InventorySourceAttributes is the inventory-sources attribute block.
type InventorySourceAttributes struct {
	Name                    string                       `json:"name"`
	Description             string                       `json:"description"`
	SourceType              string                       `json:"source-type"`
	Config                  models.InventorySourceConfig `json:"config"`
	UpdateOnLaunch          bool                         `json:"update-on-launch"`
	UpdateCacheTimeout      int                          `json:"update-cache-timeout"`
	Overwrite               bool                         `json:"overwrite"`
	OverwriteVars           bool                         `json:"overwrite-vars"`
	Verbosity               int                          `json:"verbosity"`
	GroupByInstanceID       bool                         `json:"group-by-instance-id"`
	GroupByRegion           bool                         `json:"group-by-region"`
	GroupByAvailabilityZone bool                         `json:"group-by-availability-zone"`
	GroupByTag              string                       `json:"group-by-tag"`
	HostnameVar             string                       `json:"hostname-var"`
	InstanceFilters         string                       `json:"instance-filters"`
	SyncSchedule            string                       `json:"sync-schedule"`
	Status                  string                       `json:"status"`
	LastSyncAt              *time.Time                   `json:"last-sync-at"`
	LastSyncError           string                       `json:"last-sync-error"`
	LastSyncLog             string                       `json:"last-sync-log"`
	HostsCount              int                          `json:"hosts-count"`
	Enabled                 bool                         `json:"enabled"`
	CreatedAt               string                       `json:"created-at"`
	UpdatedAt               string                       `json:"updated-at"`
}

// InventorySourceRelationships: the inventory always, the cloud credential when bound.
type InventorySourceRelationships struct {
	Inventory  jsonapi.Relationship  `json:"inventory"`
	Credential *jsonapi.Relationship `json:"credential,omitempty"`
}

// InventorySyncAttributes: source-name rides along when the relation was preloaded, and
// output only on detail fetches - both omitempty, matching the conditional map members.
type InventorySyncAttributes struct {
	Status           string     `json:"status"`
	TriggeredBy      string     `json:"triggered-by"`
	HostsDiscovered  int        `json:"hosts-discovered"`
	GroupsDiscovered int        `json:"groups-discovered"`
	Error            string     `json:"error"`
	StartedAt        *time.Time `json:"started-at"`
	FinishedAt       *time.Time `json:"finished-at"`
	CreatedAt        time.Time  `json:"created-at"`
	SourceName       string     `json:"source-name,omitempty"`
	// Output is a pointer so the detail route emits the member even when the run produced
	// no log, while listings omit it entirely.
	Output *string `json:"output,omitempty"`
}

// InventorySyncRelationships: the inventory always, the source when the run had one.
type InventorySyncRelationships struct {
	Inventory jsonapi.Relationship  `json:"inventory"`
	Source    *jsonapi.Relationship `json:"source,omitempty"`
}

// TemplateVariableAttributes is the TFE vars attribute block; a sensitive value is masked.
type TemplateVariableAttributes struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	Description string `json:"description"`
	Sensitive   bool   `json:"sensitive"`
	Category    string `json:"category"`
	HCL         bool   `json:"hcl"`
}

// ConfigurableRelationship is TFE's naming for the variable's owner.
type ConfigurableRelationship struct {
	Configurable jsonapi.Relationship `json:"configurable"`
}

// DiscoveredPlaybook is one candidate file found in a repository scan. The playbook members
// appear only for candidates already registered, which is how the UI greys them out.
type DiscoveredPlaybook struct {
	Path         string `json:"path"`
	Name         string `json:"name"`
	Registered   bool   `json:"registered"`
	PlaybookID   string `json:"playbook_id,omitempty"`
	PlaybookName string `json:"playbook_name,omitempty"`
}

// BulkImportResult is one row of the bulk-import outcome. Exactly one of error (status
// "failed") or the playbook members (status "created"/"skipped") is populated.
type BulkImportResult struct {
	Path       string `json:"path"`
	Status     string `json:"status"`
	Error      string `json:"error,omitempty"`
	PlaybookID string `json:"playbook_id,omitempty"`
	Name       string `json:"name,omitempty"`
}

// BulkImportResponse is the import summary: the per-file results plus the tallies.
type BulkImportResponse struct {
	Results []BulkImportResult `json:"results"`
	Created int                `json:"created"`
	Skipped int                `json:"skipped"`
	Failed  int                `json:"failed"`
}

// FindOrCreateMeta reports whether the find-or-create action created the playbook or found
// an existing one.
type FindOrCreateMeta struct {
	Created bool `json:"created"`
}

// CredentialAttributes is the ansible-credentials attribute block. Sensitive values are
// never included; the has-* booleans report only whether one is stored.
type CredentialAttributes struct {
	Name              string                `json:"name"`
	Description       string                `json:"description"`
	CredentialType    models.CredentialType `json:"credential-type"`
	Username          string                `json:"username"`
	AzureTenantID     string                `json:"azure-tenant-id"`
	AzureClientID     string                `json:"azure-client-id"`
	SSHPort           int                   `json:"ssh-port"`
	SSHBecomeUser     string                `json:"ssh-become-user"`
	HasSSHPrivateKey  bool                  `json:"has-ssh-private-key"`
	HasPassword       bool                  `json:"has-password"`
	HasVaultPassword  bool                  `json:"has-vault-password"`
	HasBecomePassword bool                  `json:"has-become-password"`
	CreatedAt         string                `json:"created-at"`
	UpdatedAt         string                `json:"updated-at"`
}

// CredentialRelationships is the single organization relationship of a credential.
type CredentialRelationships struct {
	Organization jsonapi.Relationship `json:"organization"`
}

// AdHocModulesAttributes lists the ad-hoc modules an organization may run.
type AdHocModulesAttributes struct {
	Modules []string `json:"modules"`
}

// CallbackJobAttributes is the provisioning-callback acknowledgment: just enough for the
// caller to poll the job it started.
type CallbackJobAttributes struct {
	Status models.AnsibleJobStatus `json:"status"`
	Limit  string                  `json:"limit"`
}

// TemplateCredentialAttributes is the slim credential projection on a job template - name
// and type only, never a secret.
type TemplateCredentialAttributes struct {
	Name           string                `json:"name"`
	CredentialType models.CredentialType `json:"credential-type"`
	VaultID        string                `json:"vault-id"`
	Username       string                `json:"username"`
}

// TeamAccessAttributes is the read-only per-team access summary for a job template.
type TeamAccessAttributes struct {
	TeamName string `json:"team-name"`
	Read     bool   `json:"read"`
	Write    bool   `json:"write"`
	Execute  bool   `json:"execute"`
}
